#!/bin/sh

cd ~

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export GBM_BACKEND=nvidia-drm
export WLR_NO_HARDWARE_CURSORS=1
export LIBVA_DRIVER_NAME=nvidia
export XDG_SESSION_TYPE=wayland
export GTK_THEME=Sweet-Dark

m=$(cat /sys/class/drm/card1-DP-1/status)
n=$(cat /sys/class/drm/card1-DP-2/status)

if [ "$m" = 'disconnected' ] && [ "$n" = 'disconnected' ]; then
	export LAPTOP=1
	exec Hyprland
else
	export LAPTOP=0
	export WLR_DRM_DEVICES=/dev/dri/card1
	exec Hyprland
fi



